"use strict";
const H=[['treino','Treino','◈',4],['cardio','Cardio (30 min)','↗',5],['alimentacao','Alimentação','◇',7],['agua','Água (3L)','◉',7],['sono','Sono antes das 23h','◐',5],['espiritual','Meditação','✦',7],['leitura','Leitura','▤',7],['estudo','Estudo','⌁',5]];
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0'), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`, date=s=>new Date(s+'T12:00:00'), add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x}, fmt=(s,o)=>new Intl.DateTimeFormat('pt-BR',o).format(date(s));
let data,selected=iso(new Date()),month=new Date();month.setDate(1);
function rec(s){return data.habitos[s]||{habitos:{},peso:null,observacao:''}}
function monday(s){let d=date(s),w=d.getDay();return add(d,w===0?-6:1-w)}
function range(a,b){let x=[];for(let d=date(a);d<=date(b);d=add(d,1))x.push(iso(d));return x}
function pctDay(s){let r=rec(s),n=H.filter(h=>r.habitos[h[0]]).length;return Math.round(n/H.length*100)}
function missionPct(){let m=data.configuracoes.missaoAtual,ds=range(m.inicio,m.fim),vals=ds.flatMap(s=>H.map(h=>rec(s).habitos[h[0]]?1:0));return vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*100):0}
function render(){let m=data.configuracoes.missaoAtual,p=missionPct();$('#mission-title').textContent=m.titulo;$('#mission-period').textContent=`${fmt(m.inicio,{day:'2-digit',month:'long'})} a ${fmt(m.fim,{day:'2-digit',month:'long',year:'numeric'})}`;$('#mission-progress').textContent=p+'%';$('#mission-bar').style.width=p+'%';$('#storage-mode').textContent=MMCD.modo()==='arquivo'?'Salvando no arquivo pelo Python':'Salvando neste navegador';renderCal();renderDay();renderWeek()}
function renderCal(){$('#month-title').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(month);let first=new Date(month),offset=(first.getDay()+6)%7,last=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),html='';for(let i=0;i<offset;i++)html+='<div class="day empty"></div>';for(let n=1;n<=last;n++){let d=new Date(month.getFullYear(),month.getMonth(),n),s=iso(d),r=rec(s),has=Object.keys(r.habitos||{}).length||r.peso||r.observacao,p=pctDay(s);html+=`<button class="day ${s===selected?'selected':''} ${s===iso(new Date())?'today':''}" data-date="${s}"><span class="day-number">${n}</span><span class="dots">${H.map(h=>`<i class="dot ${r.habitos?.[h[0]]?'on':''}"></i>`).join('')}</span><span class="day-score">${has?p+'%':'Sem registro'}</span></button>`}$('#calendar').innerHTML=html;document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;render()})}
function renderDay(){let r=rec(selected);$('#day-title').textContent=fmt(selected,{day:'2-digit',month:'2-digit',year:'numeric'});$('#day-sub').textContent=fmt(selected,{weekday:'long'});$('#habits').innerHTML=H.map(h=>`<label class="habit-row"><span class="habit-icon">${h[2]}</span><span><strong>${h[1]}</strong><small>Marque somente se realmente cumpriu.</small></span><input type="checkbox" data-h="${h[0]}" ${r.habitos?.[h[0]]?'checked':''}><span class="check">✓</span></label>`).join('');$('#weight').value=r.peso??'';$('#note').value=r.observacao||''}
function renderWeek(){let a=monday(selected),b=add(a,6),as=iso(a),bs=iso(b);$('#week-title').textContent=`${fmt(as,{day:'2-digit',month:'2-digit'})} a ${fmt(bs,{day:'2-digit',month:'2-digit'})}`;let ds=range(as,bs),scores=[];$('#week-metrics').innerHTML=H.map(h=>{let n=ds.filter(s=>rec(s).habitos?.[h[0]]).length,p=Math.min(100,Math.round(n/h[3]*100));scores.push(p);return `<div class="metric"><strong>${h[2]} ${h[1]}</strong><b>${n} / ${h[3]}</b><div class="progress"><i style="width:${p}%"></i></div><small>${p}% da meta</small></div>`}).join('');$('#week-score').textContent=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length)+'%'}
(async()=>{await MMCDShell('alvo');data=await MMCD.carregar();render();$('#prev').onclick=()=>{month.setMonth(month.getMonth()-1);renderCal()};$('#next').onclick=()=>{month.setMonth(month.getMonth()+1);renderCal()};$('#today').onclick=()=>{selected=iso(new Date());month=new Date();month.setDate(1);render()};$('#save').onclick=async()=>{let hab={};document.querySelectorAll('[data-h]').forEach(x=>hab[x.dataset.h]=x.checked);data.habitos[selected]={habitos:hab,peso:$('#weight').value?Number($('#weight').value):null,observacao:$('#note').value.trim()};let res=await MMCD.salvar(data);$('#save-note').textContent=res.modo==='arquivo'?(res.publicado?'Salvo e enviado para atualização do site público.':'Salvo no computador. '+(res.aviso||'O envio ao site ficou pendente.')):'Salvo neste navegador. Abra pelo ABRIR_PAINEL.bat para publicar.';render()};$('#export').onclick=()=>MMCD.exportar();$('#import').onchange=async e=>{if(e.target.files[0]){await MMCD.importar(e.target.files[0]);MMCD.invalidar();data=await MMCD.carregar();render()}}})();
