"use strict";
(async()=>{
 const $=sel=>document.querySelector(sel);const esc=window.MemoryLife.esc;let store=window.MemoryLife.normalizeCircle(await window.MemoryLife.read(window.MemoryLife.KEYS.circle,{versao:1,itens:[]}));const birthdays=await window.MemoryLife.read(window.MemoryLife.KEYS.birthdays,{versao:1,itens:[]});let editingId=null;
 function setStatus(text,kind=""){const el=$("#circle-status");if(!el)return;el.textContent=text;el.className=`personal-status ${kind?`is-${kind}`:""}`}
 async function save(){store.atualizadoEm=new Date().toISOString();store.itens=(store.itens||[]).map(item=>({...item,historico:Array.isArray(item.historico)?item.historico.slice(-120):[]}));await window.MemoryLife.write(window.MemoryLife.KEYS.circle,store)}
 function fmtDate(value){if(!value)return"";const d=new Date(String(value).slice(0,10)+"T12:00:00");return Number.isNaN(d.getTime())?"":d.toLocaleDateString("pt-BR")}
 function birthdayFor(name){const n=window.MemoryLife.norm(name);return (birthdays?.itens||[]).find(x=>x?.ativo!==false&&window.MemoryLife.norm(x?.nome)===n)}
 function reset(){editingId=null;$("#circle-form").reset();$("#circle-frequency").value="14";$("#circle-active").checked=true;$("#circle-submit").textContent="Adicionar ao círculo";$("#circle-cancel").hidden=true;setStatus("Use esse cadastro apenas para pessoas que realmente importam para você.")}
 function stats(){const active=(store.itens||[]).filter(x=>x?.ativo!==false);const due=active.filter(x=>window.MemoryLife.personStatus(x).state==="due");$("#circle-stat-people").textContent=active.length;$("#circle-stat-due").textContent=due.length;const today=(store.itens||[]).filter(x=>x?.ultimoCuidadoEm===window.MemoryLife.todayISO()).length;$("#circle-stat-today").textContent=today}
 function render(){stats();const items=(store.itens||[]).slice().sort((a,b)=>{const sa=window.MemoryLife.personStatus(a),sb=window.MemoryLife.personStatus(b);const rank={due:0,soon:1,ok:2};return (rank[sa.state]??3)-(rank[sb.state]??3)||String(a.nome).localeCompare(String(b.nome),"pt-BR")});const list=$("#circle-list");if(!items.length){list.innerHTML=`<div class="personal-empty">Seu Círculo de Cuidado ainda está vazio. Cadastre poucas pessoas importantes; a proposta é lembrar de cuidar, não criar mais uma lista infinita.</div>`;return}list.innerHTML=items.map(person=>{const status=window.MemoryLife.personStatus(person);const birthday=birthdayFor(person.nome);return `<article class="personal-item" data-inactive="${person.ativo===false?"1":"0"}"><span class="personal-item__icon">${person.ativo===false?"○":"❤️"}</span><div class="personal-item__copy"><span class="personal-item__eyebrow">${esc(person.relacao||"Pessoa importante")}</span><strong>${esc(person.nome)}</strong>${person.nota?`<p>${esc(person.nota)}</p>`:""}<div class="personal-item__meta"><span class="personal-chip ${status.state}">${esc(status.label)}</span><span class="personal-chip">Próximo cuidado: ${esc(status.next)}</span><span class="personal-chip">A cada ${Number(person.frequenciaDias||14)} dias</span>${birthday?`<span class="personal-chip">🎂 ${String(birthday.dia).padStart(2,"0")}/${String(birthday.mes).padStart(2,"0")}</span>`:""}${person.ativo===false?`<span class="personal-chip">Desativado</span>`:""}</div></div><div class="personal-item__actions">${person.ativo===false?`<button data-toggle="${person.id}">Ativar</button>`:`<button class="primary" data-care="${person.id}">Cuidei hoje</button><button data-toggle="${person.id}">Desativar</button>`}<button data-edit="${person.id}">Editar</button><button class="danger" data-delete="${person.id}">Excluir</button></div></article>`}).join("");attach()}
 function attach(){$("#circle-list").querySelectorAll("[data-care]").forEach(b=>b.onclick=()=>careToday(b.dataset.care));$("#circle-list").querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>toggle(b.dataset.toggle));$("#circle-list").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));$("#circle-list").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
 async function submit(event){event.preventDefault();const nome=$("#circle-name").value.trim();if(!nome){setStatus("Informe o nome da pessoa.","error");return}const now=new Date().toISOString();const base={nome,relacao:$("#circle-relation").value.trim(),frequenciaDias:Math.max(1,Number($("#circle-frequency").value||14)),nota:$("#circle-note").value.trim(),ativo:$("#circle-active").checked,atualizadoEm:now};if(editingId){Object.assign(store.itens.find(x=>x.id===editingId),base)}else store.itens.push({id:window.MemoryLife.uid(),...base,criadoEm:now,ultimoCuidadoEm:"",historico:[]});try{await save();reset();render();window.MMCDUI?.toast?.("Pessoa salva no Círculo de Cuidado.")}catch(error){console.error(error);setStatus("Não foi possível salvar agora. Nada foi apagado.","error")}}
 function edit(id){const p=store.itens.find(x=>x.id===id);if(!p)return;editingId=id;$("#circle-name").value=p.nome||"";$("#circle-relation").value=p.relacao||"";$("#circle-frequency").value=String(p.frequenciaDias||14);$("#circle-note").value=p.nota||"";$("#circle-active").checked=p.ativo!==false;$("#circle-submit").textContent="Salvar alterações";$("#circle-cancel").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
 async function careToday(id){const p=store.itens.find(x=>x.id===id);if(!p)return;const now=new Date().toISOString();p.ultimoCuidadoEm=window.MemoryLife.todayISO();p.atualizadoEm=now;p.historico=Array.isArray(p.historico)?p.historico:[];p.historico.push({data:p.ultimoCuidadoEm,criadoEm:now});await save();render();window.MMCDUI?.toast?.(`Cuidado com ${p.nome} registrado.`)}
 async function toggle(id){const p=store.itens.find(x=>x.id===id);if(!p)return;p.ativo=p.ativo===false;p.atualizadoEm=new Date().toISOString();await save();render()}
 async function remove(id){const p=store.itens.find(x=>x.id===id);if(!p||!confirm(`Remover ${p.nome} do Círculo de Cuidado?`))return;store.itens=store.itens.filter(x=>x.id!==id);await save();render()}
 $("#circle-form").addEventListener("submit",submit);$("#circle-cancel").onclick=reset;render();reset();
})().catch(error=>{console.error(error);window.MMCDUI?.toast?.("Não foi possível carregar o Círculo de Cuidado.")});
