"use strict";(async()=>{
 const d=await MMCD.carregar(),today=new Date(),pad=n=>String(n).padStart(2,'0'),isoDate=x=>`${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`,iso=isoDate(today),fmt=x=>x.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'}),meta=d.configuracoes.missaoAtual||{};
 document.querySelector('#today-label').textContent=today.toLocaleDateString('pt-BR');
 document.querySelector('#mission-card').innerHTML=`<div><p class="eyebrow">Missão de vida</p><h2>${MMCDUI.esc(meta.titulo||'Defina sua missão de vida')}</h2><span class="muted">Sua direção principal para decisões, hábitos e prioridades.</span></div><div class="mission-date"><span class="eyebrow">Hoje</span><strong>${pad(today.getDate())}</strong><span>${today.toLocaleDateString('pt-BR',{month:'long'})}</span></div>`;
 const due=MMCD.metasNaData(d,iso),done=due.filter(m=>MMCD.registro(d,iso,m.id)?.concluida).length,books=d.livros.concluidos.filter(x=>(x.dataConclusao||'').startsWith(String(d.configuracoes.anoMetaLivros))),weights=Object.entries(d.pesos).sort(),lastW=weights.at(-1)?.[1],medDates=Object.keys(d.meditacoes||{}).sort(),lastMed=medDates.at(-1)||'';
 function streak(){let n=0,c=new Date(today);for(;;){const s=isoDate(c),goals=MMCD.metasNaData(d,s);if(!goals.length){c.setDate(c.getDate()-1);if(c<new Date('2020-01-01'))break;continue}if(!goals.some(m=>MMCD.registro(d,s,m.id)?.concluida))break;n++;c.setDate(c.getDate()-1)}return n}
 const medMeta=d.metas.find(m=>m.nome.toLowerCase().includes('medita')),medDone=!!(d.meditacoes[iso]||medMeta&&MMCD.registro(d,iso,medMeta.id)?.concluida);
 const cards=[['🎯','Missão de vida',meta.titulo||'Não definida','Direção principal'],['📅','Data atual',fmt(today),'Hoje'],['🔥','Sequência de dias',`${streak()} dias`,'Com algum registro'],['📖','Livro em andamento',d.livros.atual.titulo||'Nenhum',d.livros.atual.autor||'Cadastre sua leitura'],['📚','Livros concluídos',String(books.length),`Meta anual: ${d.configuracoes.metaLivrosAno}`],['🙏','Meditação de hoje',medDone?'Concluída':'Pendente',lastMed?`Última: ${MMCDUI.date(lastMed)}`:'Sem registro'],['⚖️','Peso atual',lastW!=null?`${Number(lastW).toFixed(1).replace('.',',')} kg`:'Não informado','Último registro'],['✅','Hábitos concluídos hoje',`${done} de ${due.length}`,'Metas previstas']];
 document.querySelector('#main-cards').innerHTML=cards.map(c=>`<article class="card dash-card"><span class="dash-card__icon">${c[0]}</span><span class="dash-card__label">${c[1]}</span><strong>${MMCDUI.esc(c[2])}</strong><small>${MMCDUI.esc(c[3])}</small></article>`).join('');
 function rate(days){let ok=0,all=0;for(let i=0;i<days;i++){let x=new Date(today);x.setDate(x.getDate()-i);let s=isoDate(x),goals=MMCD.metasNaData(d,s);all+=goals.length;ok+=goals.filter(m=>MMCD.registro(d,s,m.id)?.concluida).length}return all?Math.round(ok/all*100):0}
 let weekly=rate(7),monthly=rate(30),goal=Math.min(100,Math.round(books.length/(+d.configuracoes.metaLivrosAno||30)*100));
 document.querySelector('#consistency-metrics').innerHTML=[['Consistência semanal',weekly],['Consistência mensal',monthly],['Meta anual de livros',goal]].map(x=>`<div class="metric-row"><span>${x[0]}</span><strong>${x[1]}%</strong><div class="progress"><i style="width:${x[1]}%"></i></div></div>`).join('');
 const cv=document.querySelector('#mini-weight'),ctx=cv.getContext('2d'),pts=weights.slice(-30);function draw(){let r=cv.getBoundingClientRect(),q=devicePixelRatio||1;cv.width=r.width*q;cv.height=170*q;ctx.setTransform(q,0,0,q,0,0);ctx.clearRect(0,0,r.width,170);if(pts.length<2){ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');ctx.fillText('Registre pelo menos dois pesos.',15,35);return}let vals=pts.map(x=>+x[1]),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5;ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--accent');ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>{let x=12+i*(r.width-24)/(pts.length-1),y=150-(+p[1]-min)/(max-min)*125;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}draw();addEventListener('resize',draw);
 document.querySelector('#last-meditation').innerHTML=lastMed?`<p class="meditation-date">${MMCDUI.date(lastMed)}</p><p class="meditation-note">Seu registro espiritual mais recente. Continue transformando constância em profundidade.</p><a class="text-link" href="index.html">Abrir meditação →</a>`:'<div class="empty">Nenhuma meditação registrada.</div>';
})();
