"use strict";
(async()=>{
 const $=sel=>document.querySelector(sel);const esc=window.MemoryLife.esc;let store=window.MemoryLife.normalizePrayers(await window.MemoryLife.read(window.MemoryLife.KEYS.prayers,{versao:1,itens:[]}));let activeTab="ativa";let editingId=null;let presence=null;let presenceTimer=null;let responseId=null;
 const categories={
  "Crescimento espiritual":["Aquietar o coração e reconhecer a presença de Deus.","Agradeça pelo que Deus já tem trabalhado em você.","Peça sabedoria para o próximo passo, não apenas força para chegar mais rápido."],
  "Relacionamentos":["Pense na pessoa diante de Deus, antes de pensar no problema.","Ore para ter humildade para ouvir e coragem para agir com amor.","Apresente aquilo que você não consegue controlar nessa relação."],
  "Cura":["Entregue a Deus aquilo que dói sem precisar fingir força.","Peça cuidado, direção e pessoas certas ao redor.","Agradeça por cada pequeno sinal de sustento no processo."],
  "Família":["Visualize sua casa e agradeça pelas pessoas que fazem parte dela.","Ore pelas necessidades que você conhece e também pelas que você não vê.","Peça que suas atitudes dentro de casa reflitam aquilo em que você acredita."],
  "Paz":["Respire devagar e nomeie diante de Deus o que está roubando sua paz.","Entregue o que está fora do seu controle.","Peça discernimento para agir apenas no que realmente depende de você."],
  "Gratidão":["Lembre de três coisas simples que aconteceram hoje.","Agradeça pelas pessoas que permaneceram ao seu lado.","Reconheça algo que você costuma tratar como garantido."],
  "Perdão":["Fale com Deus sobre a mágoa sem maquiar o que você sente.","Peça força para não alimentar o que está te prendendo.","Se houver algo que depende de você, peça coragem para dar o primeiro passo."],
  "Provisão":["Apresente sua necessidade com clareza.","Peça sabedoria para administrar o que já está em suas mãos.","Entregue a ansiedade pelo futuro e foque no próximo passo possível."],
  "Sabedoria":["Descreva a decisão que está diante de você.","Peça discernimento para separar desejo, medo e direção.","Ore por humildade para aceitar uma resposta diferente da que você imaginou."],
  "Outro":["Aquietar o coração.","Apresente a Deus o que está ocupando sua mente agora.","Finalize agradecendo e escolhendo um próximo passo coerente com sua oração."]
 };
 function setStatus(text,kind=""){const el=$("#prayer-status");if(!el)return;el.textContent=text;el.className=`personal-status ${kind?`is-${kind}`:""}`}
 async function save(){store.atualizadoEm=new Date().toISOString();store.itens=(store.itens||[]).map(item=>({...item,historico:Array.isArray(item.historico)?item.historico.slice(-180):[]}));await window.MemoryLife.write(window.MemoryLife.KEYS.prayers,store)}
 function stats(){const s=window.MemoryLife.prayerStats(store);$("#prayer-stat-active").textContent=s.active;$("#prayer-stat-answered").textContent=s.answered;$("#prayer-stat-days").textContent=s.oldestDays?`${s.oldestDays}d`:"—"}
 function fmtDate(value){if(!value)return"";const d=new Date(String(value).slice(0,10)+"T12:00:00");return Number.isNaN(d.getTime())?"":d.toLocaleDateString("pt-BR")}
 function resetForm(){editingId=null;$("#prayer-form").reset();$("#prayer-submit").textContent="Salvar oração";$("#prayer-cancel-edit").hidden=true;setStatus("O que é importante pode ser simples. Escreva de um jeito que você reconheça depois.")}
 function render(){stats();const items=(store.itens||[]).filter(x=>x?.status===activeTab).sort((a,b)=>String(b.atualizadoEm||b.criadoEm||"").localeCompare(String(a.atualizadoEm||a.criadoEm||"")));const list=$("#prayer-list");if(!items.length){list.innerHTML=`<div class="personal-empty">${activeTab==="ativa"?"Nenhuma oração ativa. Você pode começar com uma frase simples.":"Quando você marcar uma oração como respondida, ela vira uma memória guardada aqui."}</div>`;return}list.innerHTML=items.map(item=>{const history=(item.historico||[]).filter(h=>h?.tipo==="oracao").length;return `<article class="personal-item"><span class="personal-item__icon">${item.status==="respondida"?"✨":"🙏"}</span><div class="personal-item__copy"><span class="personal-item__eyebrow">${esc(item.categoria||"Oração")}</span><strong>${esc(item.titulo||"Oração")}</strong>${item.pessoa?`<p>Por: ${esc(item.pessoa)}</p>`:""}${item.nota?`<p>${esc(item.nota)}</p>`:""}<div class="personal-item__meta"><span class="personal-chip">Desde ${fmtDate(item.criadoEm)}</span><span class="personal-chip">${history} momento${history===1?"":"s"} de oração</span>${item.status==="respondida"?`<span class="personal-chip ok">Respondida em ${fmtDate(item.respondidaEm)}</span>`:""}</div>${item.status==="respondida"&&item.respostaNota?`<p><strong>Memória:</strong> ${esc(item.respostaNota)}</p>`:""}</div><div class="personal-item__actions">${item.status==="ativa"?`<button class="primary" data-pray="${item.id}">Orar agora</button><button data-edit="${item.id}">Editar</button><button class="success" data-answered="${item.id}">Deus respondeu</button>`:`<button data-pray="${item.id}">Relembrar em oração</button><button data-reactivate="${item.id}">Voltar para oração</button>`}<button class="danger" data-delete="${item.id}">Excluir</button></div></article>`}).join("");attachList()}
 function attachList(){$("#prayer-list").querySelectorAll("[data-pray]").forEach(b=>b.onclick=()=>openPresence(b.dataset.pray));$("#prayer-list").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editPrayer(b.dataset.edit));$("#prayer-list").querySelectorAll("[data-answered]").forEach(b=>b.onclick=()=>openResponse(b.dataset.answered));$("#prayer-list").querySelectorAll("[data-reactivate]").forEach(b=>b.onclick=()=>reactivate(b.dataset.reactivate));$("#prayer-list").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removePrayer(b.dataset.delete))}
 async function submitForm(event){event.preventDefault();const title=$("#prayer-title").value.trim();if(!title){setStatus("Dê um nome para essa oração.","error");return}const now=new Date().toISOString();const base={titulo:title,categoria:$("#prayer-category").value,pessoa:$("#prayer-person").value.trim(),nota:$("#prayer-note").value.trim(),atualizadoEm:now};if(editingId){const item=store.itens.find(x=>x.id===editingId);Object.assign(item,base)}else store.itens.push({id:window.MemoryLife.uid(),...base,status:"ativa",criadoEm:now,historico:[]});try{await save();resetForm();render();window.MMCDUI?.toast?.("Oração salva no Memory.")}catch(error){console.error(error);setStatus("Não foi possível salvar agora. Nada foi apagado.","error")}}
 function editPrayer(id){const item=store.itens.find(x=>x.id===id);if(!item)return;editingId=id;$("#prayer-title").value=item.titulo||"";$("#prayer-category").value=item.categoria||"Outro";$("#prayer-person").value=item.pessoa||"";$("#prayer-note").value=item.nota||"";$("#prayer-submit").textContent="Salvar alterações";$("#prayer-cancel-edit").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
 async function reactivate(id){const item=store.itens.find(x=>x.id===id);if(!item)return;item.status="ativa";item.atualizadoEm=new Date().toISOString();await save();activeTab="ativa";syncTabs();render()}
 async function removePrayer(id){const item=store.itens.find(x=>x.id===id);if(!item||!confirm(`Excluir “${item.titulo}”?`))return;store.itens=store.itens.filter(x=>x.id!==id);await save();render()}
 function openResponse(id){responseId=id;const dlg=$("#response-dialog");const item=store.itens.find(x=>x.id===id);$("#response-title").textContent=item?.titulo||"Oração";$("#response-note").value="";dlg.showModal()}
 async function confirmResponse(){const item=store.itens.find(x=>x.id===responseId);if(!item)return;const now=new Date().toISOString();item.status="respondida";item.respondidaEm=now;item.respostaNota=$("#response-note").value.trim();item.atualizadoEm=now;item.historico=Array.isArray(item.historico)?item.historico:[];item.historico.push({tipo:"resposta",data:window.MemoryLife.todayISO(),criadoEm:now,nota:item.respostaNota});await save();$("#response-dialog").close();activeTab="respondida";syncTabs();render();window.MMCDUI?.toast?.("Guardado em Memórias de Deus.")}
 function promptSteps(item){const base=categories[item?.categoria]||categories.Outro;const personal=item?.nota?`Apresente também isto: ${item.nota}`:"Fale com Deus com suas próprias palavras.";return [base[0],personal,base[1],base[2],"Fique alguns instantes em silêncio. Você não precisa preencher todo espaço com palavras."]}
 function renderPresence(){if(!presence)return;const item=presence.item,step=presence.steps[presence.index];$("#presence-category").textContent=item.categoria||"Oração";$("#presence-title").textContent=presence.index===0?item.titulo:"Continue em oração";$("#presence-prompt").textContent=step;$("#presence-step").textContent=`Etapa ${presence.index+1} de ${presence.steps.length}`;$("#presence-next").textContent=presence.index===presence.steps.length-1?"Concluir oração":"Próximo"}
 function openPresence(id){const item=store.itens.find(x=>x.id===id);if(!item)return;presence={item,steps:promptSteps(item),index:0,startedAt:Date.now()};$("#presence-layer").hidden=false;document.body.style.overflow="hidden";renderPresence();clearInterval(presenceTimer);presenceTimer=setInterval(()=>{if(!presence)return;const seconds=Math.floor((Date.now()-presence.startedAt)/1000);$("#presence-time").textContent=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`},1000)}
 async function completePresence(){if(!presence)return;const item=presence.item;const now=new Date().toISOString();item.historico=Array.isArray(item.historico)?item.historico:[];item.historico.push({tipo:"oracao",data:window.MemoryLife.todayISO(),criadoEm:now,duracaoSeg:Math.floor((Date.now()-presence.startedAt)/1000)});item.atualizadoEm=now;try{await save()}catch(error){console.error(error)}closePresence();render();window.MMCDUI?.toast?.("Momento de oração registrado.")}
 function nextPresence(){if(!presence)return;if(presence.index>=presence.steps.length-1){completePresence();return}presence.index+=1;renderPresence()}
 function closePresence(){clearInterval(presenceTimer);presenceTimer=null;presence=null;$("#presence-layer").hidden=true;document.body.style.overflow=""}
 function syncTabs(){document.querySelectorAll("[data-prayer-tab]").forEach(b=>b.classList.toggle("active",b.dataset.prayerTab===activeTab))}
 $("#prayer-form").addEventListener("submit",submitForm);$("#prayer-cancel-edit").onclick=resetForm;document.querySelectorAll("[data-prayer-tab]").forEach(b=>b.onclick=()=>{activeTab=b.dataset.prayerTab;syncTabs();render()});$("#response-cancel").onclick=()=>$("#response-dialog").close();$("#response-confirm").onclick=confirmResponse;$("#presence-next").onclick=nextPresence;$("#presence-close").onclick=closePresence;$("#presence-finish").onclick=completePresence;document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("#presence-layer").hidden)closePresence()});render();resetForm();
})().catch(error=>{console.error(error);window.MMCDUI?.toast?.("Não foi possível carregar suas orações.")});
