"use strict";
window.MMCDShell=async function(active){
 const nav=[['missoes','painel.html','01','Missões','Visão da vida'],['meditacao','index.html','02','Meditação','Momento com Deus'],['livros','livros.html','03','Livros','Biblioteca'],['atividades','atividades.html','04','Atividades','Rotina diária'],['metas','metas.html','05','Metas','Cadastro'],['estatisticas','relatorios.html','06','Estatísticas','Evolução']];
 document.body.insertAdjacentHTML('afterbegin',`<aside class="sidebar"><a class="sidebar-brand" href="painel.html"><span class="sidebar-brand__mark">LS</span><div><small>PERSONAL OPERATING SYSTEM</small><strong>LIFE STYLE</strong></div></a><nav class="sidebar-nav">${nav.map(x=>`<a class="sidebar-link ${active===x[0]?'active':''}" href="${x[1]}"><span class="sidebar-link__icon">${x[2]}</span><div><strong>${x[3]}</strong><small>${x[4]}</small></div><span class="sidebar-link__arrow">›</span></a>`).join('')}</nav><div class="sidebar-summary">Fé, disciplina e evolução.<br>Um dia de cada vez.</div></aside>`);
 document.body.classList.add('app-body');
 const tema=localStorage.getItem('mmcd:tema')||'claro';document.documentElement.dataset.tema=tema;
 document.querySelectorAll('#theme-toggle').forEach(btn=>btn.onclick=()=>{const n=document.documentElement.dataset.tema==='escuro'?'claro':'escuro';document.documentElement.dataset.tema=n;localStorage.setItem('mmcd:tema',n);btn.textContent=n==='escuro'?'☀':'☾'});
};
window.MMCDUI={esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date:s=>s?new Date(s+'T12:00:00').toLocaleDateString('pt-BR'):'—',toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}};
