"use strict";
window.MMCDShell=async function(active){
 const nav=[['missoes','painel.html','01','Missões','Visão da vida'],['meditacao','index.html','02','Meditação','Momento com Deus'],['ingles','ingles.html','03','Inglês diário','Prática e revisão'],['livros','livros.html','04','Livros','Biblioteca'],['atividades','atividades.html','05','Atividades','Rotina diária'],['metas','metas.html','06','Metas','Cadastro'],['estatisticas','relatorios.html','07','Estatísticas','Evolução']];
 document.body.insertAdjacentHTML('afterbegin',`<aside class="sidebar"><a class="sidebar-brand" href="painel.html"><span class="sidebar-brand__mark"><img src="logo-ls-sidebar.png?v=20260804-ls-brand2" alt="Logo Life Style"></span><div class="sidebar-brand__copy"><small>SISTEMA DE EVOLUÇÃO</small><strong>LIFE STYLE</strong></div></a><nav class="sidebar-nav">${nav.map(x=>`<a class="sidebar-link ${active===x[0]?'active':''}" href="${x[1]}"><span class="sidebar-link__icon">${x[2]}</span><div><strong>${x[3]}</strong><small>${x[4]}</small></div><span class="sidebar-link__arrow">›</span></a>`).join('')}</nav><div class="sidebar-summary">Fé, disciplina e evolução.<br>Um dia de cada vez.</div></aside>`);
 document.body.classList.add('app-body');
 try{const session=await MMCDAuth.requireSession();const sidebar=document.querySelector('.sidebar');if(sidebar){sidebar.append(MMCDAuth.accountButton(session.user));sidebar.insertAdjacentHTML('beforeend','<div class="sync-status">Dados online · Supabase</div>')}}catch(e){console.error(e)}
 const tema=localStorage.getItem('mmcd:tema')||'claro';document.documentElement.dataset.tema=tema;
 document.querySelectorAll('#theme-toggle').forEach(btn=>{btn.textContent=tema==='escuro'?'☀':'☾';btn.onclick=()=>{const n=document.documentElement.dataset.tema==='escuro'?'claro':'escuro';document.documentElement.dataset.tema=n;localStorage.setItem('mmcd:tema',n);btn.textContent=n==='escuro'?'☀':'☾'}});
};
window.MMCDUI={esc:s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),date:s=>s?new Date(s+'T12:00:00').toLocaleDateString('pt-BR'):'—',toast(msg,duration=2200){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}clearTimeout(t._timer);t.textContent=msg;t.classList.add('show');t._timer=setTimeout(()=>t.classList.remove('show'),duration)}};
