"use strict";

window.MMCD_TREINO_GUIAS = {
  "remada-baixa-crossover": {titulo:"Remada baixa no crossover",consulta:"Seated cable row",consultas:["Seated cable row","Cable seated row","Seated row"],visualKey:"seated-cable-row",passos:["Peito aberto e coluna neutra.","Puxe em direção ao abdômen aproximando as escápulas.","Retorne controlando sem arredondar a lombar."],dica:"Evite transformar a remada em balanço do tronco."},
  "remada-crossover-b": {titulo:"Remada no crossover",consulta:"Seated cable row",consultas:["Seated cable row","Cable seated row","Seated row"],visualKey:"seated-cable-row",passos:["Peito aberto e coluna neutra.","Puxe os cotovelos para trás.","Retorne controlando a carga."],dica:"O tronco deve permanecer estável."},
  "puxada-alta-crossover": {titulo:"Puxada alta no crossover",consulta:"Lat pulldown",consultas:["Lat pulldown","Cable lat pulldown","Pulldown"],visualKey:"lat-pulldown",passos:["Comece com braços altos e peito aberto.","Puxe os cotovelos para baixo.","Leve a barra ou cabo ao alto do peito e suba controlando."],dica:"Evite jogar o tronco para trás."},
  "puxada-alta-crossover-b": {titulo:"Puxada alta no crossover",consulta:"Lat pulldown",consultas:["Lat pulldown","Cable lat pulldown","Pulldown"],visualKey:"lat-pulldown",passos:["Comece com braços altos.","Puxe os cotovelos para baixo.","Retorne até alongar as costas."],dica:"Pense em levar os cotovelos para os bolsos."},
  "remada-unilateral-crossover": {titulo:"Remada unilateral no crossover",consulta:"One arm cable row",consultas:["One arm cable row","Single arm cable row","One arm row"],visualKey:"one-arm-cable-row",passos:["Mantenha o tronco neutro.","Puxe o cotovelo para trás sem girar o quadril.","Retorne até alongar a escápula."],dica:"O movimento vem do ombro e da escápula."},
  "remada-unilateral-crossover-b": {titulo:"Remada unilateral no crossover",consulta:"One arm cable row",consultas:["One arm cable row","Single arm cable row","One arm row"],visualKey:"one-arm-cable-row",passos:["Fique estável.","Puxe o cotovelo para trás.","Retorne controlando."],dica:"Evite girar o tronco."},
  "rosca-biceps-crossover-a": {titulo:"Rosca de bíceps no crossover",consulta:"Cable biceps curl",consultas:["Cable biceps curl","Cable curl","Biceps curl"],visualKey:"cable-biceps-curl",passos:["Cotovelos próximos ao corpo.","Flexione sem levar o ombro para frente.","Desça lentamente."],dica:"Se o corpo balançar, reduza a carga."},
  "rosca-biceps-crossover-b": {titulo:"Rosca de bíceps no crossover",consulta:"Cable biceps curl",consultas:["Cable biceps curl","Cable curl","Biceps curl"],visualKey:"cable-biceps-curl",passos:["Cotovelos estáveis.","Flexione até contrair o bíceps.","Retorne controlando."],dica:"Não use impulso do tronco."},
  "triceps-polia-a": {titulo:"Tríceps na polia",consulta:"Triceps pushdown",consultas:["Triceps pushdown","Cable triceps pushdown","Triceps extension"],visualKey:"triceps-pushdown",passos:["Cotovelos junto ao corpo.","Estenda os braços para baixo.","Volte sem movimentar o ombro."],dica:"Evite inclinar o corpo para empurrar a carga."},
  "triceps-polia-b": {titulo:"Tríceps na polia",consulta:"Triceps pushdown",consultas:["Triceps pushdown","Cable triceps pushdown","Triceps extension"],visualKey:"triceps-pushdown",passos:["Fixe os cotovelos.","Estenda os braços.","Retorne lentamente."],dica:"O cotovelo é o eixo do movimento."},
  "face-pull": {titulo:"Face Pull",consulta:"Face pull",consultas:["Face pull","Cable face pull"],visualKey:"face-pull",passos:["Cabo aproximadamente na altura do rosto.","Puxe em direção ao rosto com cotovelos abertos.","Retorne mantendo tensão."],dica:"Execute leve e controlado; interrompa se houver desconforto no ombro."},
  "pallof-press-a": {titulo:"Pallof Press",consulta:"Pallof press",consultas:["Pallof press","Cable Pallof press"],visualKey:"pallof-press",passos:["Fique de lado para o cabo.","Contraia abdômen e glúteos.","Estenda os braços sem deixar o tronco girar."],dica:"Quadril e ombros continuam apontados para frente."},
  "pallof-press-hiit": {titulo:"Pallof Press",consulta:"Pallof press",consultas:["Pallof press","Cable Pallof press"],visualKey:"pallof-press",passos:["Fique de lado para o cabo.","Estenda os braços à frente.","Resista à rotação."],dica:"Não permita que o cabo gire o tronco."},
  "prancha-a": {titulo:"Prancha",consulta:"Plank",consultas:["Plank","Front plank"],visualKey:"front-plank",passos:["Cotovelos abaixo dos ombros.","Contraia abdômen e glúteos.","Mantenha o corpo alinhado."],dica:"Encerre a série se a lombar começar a afundar."},
  "prancha-hiit": {titulo:"Prancha",consulta:"Plank",consultas:["Plank","Front plank"],visualKey:"front-plank",passos:["Cotovelos abaixo dos ombros.","Mantenha o quadril alinhado.","Respire sem perder tensão."],dica:"Qualidade da posição vale mais que tempo."},
  "prancha-lateral-hiit": {titulo:"Prancha lateral",consulta:"Side plank",consultas:["Side plank","Lateral plank"],visualKey:"side-plank",passos:["Antebraço abaixo do ombro.","Eleve o quadril.","Mantenha o corpo alinhado lateralmente."],dica:"Evite deixar o quadril cair."},
  "leg-press-forca": {titulo:"Leg Press",consulta:"Leg press",consultas:["Leg press","45 degree leg press"],visualKey:"leg-press",passos:["Lombar e quadril apoiados.","Desça com os joelhos alinhados aos pés.","Empurre sem travar totalmente os joelhos."],dica:"Use a amplitude que mantém o quadril apoiado."},
  "leg-press-unilateral": {titulo:"Leg Press unilateral",consulta:"Single leg press",consultas:["Single leg press","One leg leg press","Single leg leg press"],visualKey:"single-leg-press",passos:["Um pé estável na plataforma.","Quadril apoiado.","Desça e empurre mantendo o joelho alinhado."],dica:"Busque simetria antes de aumentar a carga."},
  "afundo-bulgaro-smith": {titulo:"Afundo Búlgaro no Smith",consulta:"Bulgarian split squat",consultas:["Bulgarian split squat","Rear foot elevated split squat"],visualKey:"bulgarian-split-squat",passos:["Pé de trás apoiado e pé da frente estável.","Desça o quadril com controle.","Suba pela perna da frente."],dica:"O joelho deve acompanhar a direção do pé."},
  "avanco-reverso-smith": {titulo:"Avanço Reverso no Smith",consulta:"Reverse lunge",consultas:["Reverse lunge","Backward lunge"],visualKey:"reverse-lunge",passos:["Comece estável.","Dê um passo para trás e desça.","Retorne pela perna da frente."],dica:"Mantenha o tronco firme."},
  "cadeira-flexora-forca": {titulo:"Cadeira Flexora",consulta:"Seated leg curl",consultas:["Seated leg curl","Leg curl"],visualKey:"seated-leg-curl",passos:["Ajuste o eixo da máquina ao joelho.","Flexione os joelhos.","Retorne lentamente."],dica:"Mantenha o quadril apoiado."},
  "cadeira-flexora-resistencia": {titulo:"Cadeira Flexora",consulta:"Seated leg curl",consultas:["Seated leg curl","Leg curl"],visualKey:"seated-leg-curl",passos:["Flexione com controle.","Contraia o posterior.","Retorne lentamente."],dica:"Priorize os 3 segundos de retorno previstos."},
  "cadeira-extensora-forca": {titulo:"Cadeira Extensora",consulta:"Leg extension",consultas:["Leg extension","Seated leg extension"],visualKey:"leg-extension",passos:["Alinhe o eixo da máquina ao joelho.","Estenda os joelhos.","Retorne controlando."],dica:"Evite usar impulso."},
  "cadeira-extensora-resistencia": {titulo:"Cadeira Extensora",consulta:"Leg extension",consultas:["Leg extension","Seated leg extension"],visualKey:"leg-extension",passos:["Mantenha costas e quadril apoiados.","Estenda os joelhos.","Desça lentamente."],dica:"Não deixe as placas baterem."},
  "cadeira-adutora-forca": {titulo:"Cadeira Adutora",consulta:"Hip adduction machine",consultas:["Hip adduction","Hip adduction machine","Adductor machine"],visualKey:"hip-adduction",passos:["Escolha uma abertura confortável.","Feche as pernas contra a resistência.","Abra novamente com controle."],dica:"Não force amplitude desconfortável."},
  "cadeira-adutora-resistencia": {titulo:"Cadeira Adutora",consulta:"Hip adduction machine",consultas:["Hip adduction","Hip adduction machine","Adductor machine"],visualKey:"hip-adduction",passos:["Lombar apoiada.","Feche as pernas.","Retorne devagar."],dica:"Controle os dois sentidos."},
  "cadeira-abdutora-forca": {titulo:"Cadeira Abdutora",consulta:"Hip abduction machine",consultas:["Hip abduction","Hip abduction machine","Abductor machine"],visualKey:"hip-abduction",passos:["Quadril e lombar estáveis.","Abra os joelhos.","Feche lentamente."],dica:"Evite inclinar o tronco."},
  "cadeira-abdutora-resistencia": {titulo:"Cadeira Abdutora",consulta:"Hip abduction machine",consultas:["Hip abduction","Hip abduction machine","Abductor machine"],visualKey:"hip-abduction",passos:["Abra os joelhos mantendo o quadril firme.","Segure brevemente.","Retorne controlando."],dica:"Não bata as placas."},
  "panturrilha-leg-press": {titulo:"Panturrilha no Leg Press",consulta:"Calf press leg press",consultas:["Calf press on leg press","Leg press calf raise","Calf press"],visualKey:"leg-press-calf",passos:["Ponta dos pés apoiada.","Calcanhar desce com controle.","Empurre pela ponta dos pés."],dica:"Não force se a canela estiver dolorida."},
  "supino-inclinado-smith": {titulo:"Supino inclinado no Smith",consulta:"Incline bench press",consultas:["Incline bench press","Incline chest press"],visualKey:"incline-bench-press",passos:["Escápulas presas ao banco.","Desça a barra ao alto do peito.","Empurre mantendo os ombros estáveis."],dica:"Interrompa se houver dor no ombro."},
  "supino-reto-smith": {titulo:"Supino reto no Smith",consulta:"Bench press",consultas:["Bench press","Flat bench press","Chest press"],visualKey:"bench-press",passos:["Pés firmes e escápulas apoiadas.","Desça a barra com controle.","Empurre sem perder a posição do ombro."],dica:"Dor no ombro não faz parte da execução."}
};

window.MMCD_TREINO_GUIA_PADRAO = {
  titulo:"Guia visual",
  consulta:"",
  passos:["Mantenha uma posição estável.","Execute de forma controlada.","Interrompa se houver dor."],
  dica:"Ainda não há uma referência visual mapeada para este exercício."
};
